services:
  backend:
    container_name: go_next_grpc_sample-backend-dev
    image: go_next_grpc_sample-backend-dev
    build:
      context: ./backend
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./backend:/app
      - ./proto:/proto
    stdin_open: true
    tty: true
  frontend:
    container_name: go_next_grpc_sample-frontend-dev
    image: go_next_grpc_sample-frontend-dev
    build:
      context: ./frontend
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./frontend:/app
      - ./proto:/proto
    stdin_open: true
    tty: true
